#name: "Dependabot Automerge - Action"
#
#on:
#  pull_request:
#
#jobs:
#  worker:
#    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: write
#
#    if: github.actor == 'dependabot[bot]'
#    steps:
#      - name: automerge
#        uses: actions/github-script@0.2.0
#        with:
#          script: |
#            github.pullRequests.createReview({
#              owner: context.payload.repository.owner.login,
#              repo: context.payload.repository.name,
#              pull_number: context.payload.pull_request.number,
#              event: 'APPROVE'
#            })
#            github.pullRequests.merge({
#              owner: context.payload.repository.owner.login,
#              repo: context.payload.repository.name,
#              pull_number: context.payload.pull_request.number
#            })
#            github-token: ${{github.token}}
#        env:
#          PR_URL: ${{github.event.pull_request.html_url}}
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


name: PRs auto merge

on:
  pull_request:

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: davideviolante/pr-automerge-action@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: 'squash' # Default 'squash'
          min-approvals: 0 # Default 2
          base-ref: 'master' # Default 'dev'